### ISSUE TITLE
Hint: popcount_8

### ISSUE THREAD

**Issue by je-so** [qpfiffer/Simple-Sparsehash#1]
Your implementation of popcount_8(uint8_t x) works for uint32_t not only for uint8_t. 
The following code is not needed in case of uint8_t.

x += x >>  8;
(x + (x >> 16)) & 0x3f;

But it would be better to access the bitmap as uint32_t or uint64_t to speed things up.
(You need to add x += (x >> 32) in case of uint64_t).

**Comment by qpfiffer** [comment]
Meant to comment yesterday but apparently it didn't hold. This should now be migrated over to a popcount that uses `uint32_t` instead of `uint8_t`. Out of curiousity, why are 32-bit or 64-bit ints faster than using 8-bit integers?

**Comment by je-so** [comment]
The current implementation is not faster. You have to change 
   unsigned char bitmap[] into uint32_t bitmap[] 
first and adapt all functions accessing it. So instead of counting the bits of up to 6 bytes (GROUP_SIZE == 48) you only have to count the bits of up to 2 uint32_t (<= 64 entries).

By the way:
The loop in position_to_offset
  for (; pos > 8; pos -= 8)
        retval += popcount_8(bitmap[bitmap_iter++]);
should be changed to 
  for (; pos >= 8; pos -= 8)
        retval += popcount_8(bitmap[bitmap_iter++]);

**Comment by je-so** [comment]
Look at the last line in function position_to_offset 
return retval + popcount_32(bitmap[bitmap_iter] & ((1 << pos) - 1));

The expression ((1 << pos) -1) is of type int. Better to change to (((uint32_t)1 << pos) - 1u)
to make sure int literal 1 has enough bits (C spec. allows for 16 bit int). Now this expression
matches expression bitmap[] in type.

**Comment by qpfiffer** [comment]
Ah, okay. Thanks for your tips, by the way.
